# Generated by Django 4.2.11 on 2026-04-29 21:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payout', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='idempotencykey',
            name='unique_active_idempotency_key',
        ),
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='idempotency_merchan_16ab98_idx',
            old_name='idempotency_merchant_key_idx',
        ),
        migrations.RenameIndex(
            model_name='idempotencykey',
            new_name='idempotency_expires_6c9d28_idx',
            old_name='idempotency_expires_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_entr_merchan_68130b_idx',
            old_name='ledger_merchant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='ledgerentry',
            new_name='ledger_entr_externa_d54a13_idx',
            old_name='ledger_external_id_idx',
        ),
        migrations.RenameIndex(
            model_name='merchant',
            new_name='merchants_email_fc58cd_idx',
            old_name='merchants_email_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_merchan_a5cc5c_idx',
            old_name='payouts_merchant_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_status_4b3409_idx',
            old_name='payouts_status_created_idx',
        ),
        migrations.RenameIndex(
            model_name='payout',
            new_name='payouts_merchan_44832a_idx',
            old_name='payouts_merchant_status_idx',
        ),
        migrations.AddConstraint(
            model_name='idempotencykey',
            constraint=models.UniqueConstraint(condition=models.Q(('expires_at__gt', datetime.datetime(2026, 4, 29, 21, 0, 24, 225665, tzinfo=datetime.timezone.utc))), fields=('merchant', 'key'), name='unique_active_idempotency_key'),
        ),
    ]
